### ISSUE TITLE
Image not displayed

### ISSUE THREAD

**Issue by joserafael** [inimist/cakephp-captcha-3#1]
Hello, The image is not displayed.
What could be happend?

Thank you :-)

![captura de pantalla de 2015-11-26 11 59 11](https://cloud.githubusercontent.com/assets/60098/11427482/4c74780c-9435-11e5-8e3b-dbd0ed96a27f.png)

**Comment by inimist** [comment]
Were you able to make it work? I had been out of office for more than a week so could not reply back.

**Comment by joserafael** [comment]
No :-(
What im doing wrong?

Thank you.

**Comment by inimist** [comment]
can you send me the url where your form is located?

On Fri, Dec 4, 2015 at 8:30 PM, Jose Rafael Camejo <notifications@github.com
> wrote:

> No :-(
> What im doing wrong?
>
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inimist/cakephp-captcha-3/issues/1#issuecomment-161987579>
> .
>



-- 
Thanks & Regards,



Inimist Technologies
Web Design & Development in PHP/MYSQL

S.C.O, 32, Floor 1st, Phase 1 (Sector 55)
Mohali (Chandigarh) – 160065
P: +91-0172-4601531 , +91-9876831310,
W: http://inimist.com
E: arvind.mailto@gmail.com
Skype: arvindom

-----------------------------------------------------------
http://inimist.com
http://desismsjokes.blogspot.in
http://devarticles.in
http://jogindernagar.com

**Comment by dividedbynothing** [comment]
I also have the same issue.  It's on my local machine so I can't provide an example.  However, in the page source I found reference to a cake error:  Warning (2): imagettfbbox(): Could not read font .

also, if I switch it to math version, I get an Internal Error: Error: Cannot modify an existing config "gmail" which shows its conflicting with my mail transport.  

If I remove my mail transport config, then the math challenge shows.  However, when I submit the form with the correct answer, I get:
Error: Call to a member function setCaptcha() on a non-object
File C:\xampp\htdocs\myapp\src\Controller\UsersController.php
Line: 106 

Anyway....

**Comment by etgardo** [comment]
does not work, does not validate

**Comment by etgardo** [comment]
To login form, can work as follows:
------------------------------------------------------------------------------------
public function login()
    {
        if ($this->request->is('post')) {
            $user = $this->Auth->identify();
            
            //$this->Users->setCaptcha('securitycode', $this->Captcha->getCode('securitycode')); 
            if($this->request->data['securitycode']!=$this->Captcha->getCode('securitycode'))
            {
                $this->Flash->error(('The security code is incorrect, try again'));
                return $this->redirect(['controller'=>'Users','action'=>'login']);
            }    
            else if ($user) {
                $this->Auth->setUser($user);          
                return $this->redirect(['controller'=>'Users','action'=>'index']);
            }
            $this->Flash->error(('User or password incorrect, try again'));
        }
    }

------------------------------------------------------------------------------------

**Comment by etgardo** [comment]
to solve the problem of image, download from elsewhere sources that are in Lib / Fonts /, I have downloaded from google and it works now

**Comment by mandeepkhaleriya08** [comment]
hello 
topic is very easy and intresting for everyone?
Bt Captcha  image is not show here?can you resolve that problem  soon?hope you will  solve it soon?we are waiting for your updation?And How a user login with facebook,gmail etc?help us???

**Comment by mandeepkhaleriya08** [comment]
@ etgardo
How you solved that problem?can you help me ?

**Comment by senchuthomas** [comment]
Hi ,

  I am also facing the same issue Joserafel commented the image is not displayed.
When I tried  echo $this->Captcha->getCode('securitycode'); it is empty. What will bet the reason for this issue?  Thanks in advance for the help.

**Comment by inimist** [comment]
can you send me the link to page where you are trying it? The most possible
reason might the "headers already sent.." kind of stuff, that is output to
browser before the creation of the image using GD headers.

Thanks & Regards,



Inimist Technologies
Web Design & Development in PHP/MYSQL

S.C.O, 32, Floor 1st, Phase 1 (Sector 55)
Mohali (Chandigarh) – 160065
P: +91-0172-4601531 , +91-9876831310,
W: http://inimist.com
E: arvind.mailto@gmail.com
Skype: arvindom

-----------------------------------------------------------
http://inimist.com
http://fundabook.com - Amazing facts & Articles in Hindi
http://hindisuperjokes.com - Fresh & Funny Hindi Jokes
http://devarticles.in - My Personal Blog
http://jogindernagar.com - About my Beautiful Hometown
http://himtimes.com - Everything About Himachal Pradesh
http://hindidesijokes - Fresh & Funny Hindi Jokes

**Comment by inimist** [comment]
Which version of CakePHP are you using?

**Comment by inimist** [comment]
Ok, it is related to FONT

If I did, http://localhost/myapp/users/captcha?type=image&field=securitycode&width=120&height=40&theme=random&length=6

I have

Warning (2): imagettfbbox(): Could not read font [APP/Controller\Component\CaptchaComponent.php, line 372]Error in imagettfbbox function

So, download fonts from:


[AnonymousPro-Regular.ttf](https://github.com/google/fonts/blob/7a4070f65f2ca85ffdf2d465ff5e095005bae197/ofl/anonymouspro/AnonymousPro-Regular.ttf)
[DroidSans.ttf](https://github.com/google/fonts/blob/7a4070f65f2ca85ffdf2d465ff5e095005bae197/apache/droidsans/DroidSans.ttf)
[Ubuntu-Regular.ttf](https://github.com/google/fonts/blob/7a4070f65f2ca85ffdf2d465ff5e095005bae197/ufl/ubuntu/Ubuntu-Regular.ttf)

and replace fonts in Lib/fonts folder with them by renaming accordingly.

**Comment by senchuthomas** [comment]
Thanks It worked when I replace the fonts
